---
version: '3'
services:
  # OpenThread Border Router
  otbr:
    image: openthread/otbr:latest
    container_name: otbr
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ttyACM0
      - /dev/net/tun
    volumes:
      - ./configs/otbr:/etc/otbr
      - otbr-data:/var/lib/otbr
      - /dev/ttyACM0:/dev/ttyUSB0 # we have to remap to ttyUSB0
    env_file:
      - configs/otbr/otbr-env.list
    environment:
      OT_RCP_DEVICE: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=1000000
      OT_INFRA_IF: wlan0
      OT_THREAD_IF: wpan0
      OT_LOG_LEVEL: '7'
      OTBR_WEB: '1'
      OTBR_REST: '1'
      FIREWALL: '0'
      NAT64: '0'
      DNS64: '0'
    restart: unless-stopped
    depends_on:
      - prometheus-exporter
  # Prometheus Exporter for OTBR metrics
  prometheus-exporter:
    image: prom/node-exporter:latest
    container_name: prometheus-exporter
    ports:
      - '9100:9100'
    restart: unless-stopped
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    depends_on:
      - prometheus-exporter
  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - prometheus
  # cAdvisor for container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - '8082:8080'
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    privileged: true
    ports:
      - '9000:9000'
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
volumes:
  otbr-data: null
  prometheus-data: null
  grafana-data: null
  portainer-data: null 